services:
  app:
    build: .
    container_name: eduforge-post-app
    ports:
      - "8081:8080"
    environment:
      - RECOMMENDATION_SERVICE_URL=https://bondhub.cloud:8090
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=eduforge_post
      # Rõ ràng vô hiệu hóa xác thực MongoDB
      - MONGODB_USERNAME=
      - MONGODB_PASSWORD=
    depends_on:
      - mongodb
    networks:
      - eduforge-network
    restart: always

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    # Không public port ra ngoài
    environment:
      - MONGO_INITDB_DATABASE=eduforge_post
      # Không sử dụng xác thực
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - mongodb-data:/data/db
    networks:
      - eduforge-network
    restart: always

networks:
  eduforge-network:
    external: false

volumes:
  mongodb-data: