services:
  app:
    build: .
    container_name: eduforge-post-app
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - RECOMMENDATION_SERVICE_URL=https://recommender.eduforge.io.vn
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - eduforge-network
    restart: always

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb-data:/data/db
    networks:
      - eduforge-network
    restart: always

networks:
  eduforge-network:
    external: true

volumes:
  mongodb-data: